# booking-ui/nginx/nginx.conf
server {
    listen 80;
    listen [::]:80;

    # Definiujemy katalog, gdzie Nginx ma szukać plików statycznych
    root /usr/share/nginx/html;

    # Określamy domyślne pliki indeksu (np. index.html)
    index index.html index.htm;

    # Obsługa statycznych plików i przekierowanie zapytań
    # Ta konfiguracja jest odpowiednia dla Twojej prostej strony HTML
    # z dodatkowymi przekierowaniami dla API.
    location / {
        try_files $uri $uri/ /index.html; 
    }

    # Przekierowanie zapytań /api do booking-api-container
    location /api/ {
        proxy_pass http://booking-api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Przekierowanie zapytań /status do booking-api-container (jeśli to jest odrębny endpoint)
    location /status {
        proxy_pass http://booking-api:3000/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}