apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mysecretpassword123"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
stringData:
  REDIS_PASSWORD: "redis_secret_pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  RABBITMQ_USER: "user" 
  RABBITMQ_PASS: "rabbit_secret_pass" 
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets 
type: Opaque
stringData:
  JWT_SECRET: "PassWwa22331" 