apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: "booking_db"
  DB_HOST_POSTGRES: "postgresql-service"
  DB_PORT_POSTGRES: "5432"

  REDIS_HOST: "redis-service" 
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "rabbitmq-service" 

  JWT_EXPIRES_IN: "1h"

  
  USER_SERVICE_URL_INTERNAL: "http://user-service:3003" 
  CORE_SERVICE_URL_INTERNAL: "http://booking-core-service:3001"

  
  USER_SERVICE_PORT: "3003"
  CORE_SERVICE_PORT: "3001"
  API_GATEWAY_PORT: "3000"

  
  KEYCLOAK_INTERNAL_URL_BASE_FOR_API: "http://keycloak-service:8080"
  KEYCLOAK_PUBLIC_URL_BASE_FOR_API: "http://localhost:8181"
  KEYCLOAK_REALM_NAME_FOR_API: "booking-app-realm"
  KEYCLOAK_API_REALM_URL: "http://keycloak-service:8080/realms/booking-app-realm"